#!/usr/bin/env bash
# Configuring HAproxy to automatically redirect HTTP traffic to HTTPS.

frontend www-http
    bind *:80
    mode http
    default_backend web-backend
frontend www-https
    bind *:443 ssl crt /etc/haproxy/chamie.tech.pem
    http-request set-header X-Forwarded-Proto https
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    default_backend web-backend

backend web-backend
    redirect scheme https unless { ssl_fc }
    balance roundrobin
    server 5436-web-01 54.224.64.61:80 check
    server 5436-web-02 23.22.142.220:80 check
backend letsencrypt-backend
   server letsencrypt 127.0.0.1:54321
